### PR TITLE
REFACTOR: replaced sass with Component Library

### PR DESCRIPTION
**Pull request by ArjunGTX**
Refactored Whole UI

### CODE REVIEW

**Review by tanishk15sharma — APPROVED** [review]
you can merge.

**Review by ishapatell1 — APPROVED** [review]
Looks Good Arjun.  Your code is clean and readable.  Please add a preview of the project too.

**Review by Kavita539 — APPROVED** [review]
Loved the way you have structured the code, it looks clean and readable.
Also the needful comments were helpful while reviewing the whole code.
Folders are well structured too, the UI also looks clean and minimal.

**Comment by ArjunGTX** [comment]
> Loved the way you have structured the code, it looks clean and readable. Also the needful comments were helpful while reviewing the whole code. Folders are well structured too, the UI also looks clean and minimal.

thankyou Kavita for your valuable feedback

**Pull request merged**
