### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by ArjunGTX**
- Added Login
- Added Signup
- Input Validations
- Live preview: https://deploy-preview-10--helmet-store.netlify.app/

### CODE REVIEW

**Review by Richa-rani02 — APPROVED** [review]
Clean code and validation part of every input field is good

**Review by sharathnair9999 — APPROVED** [review]
Clean code and to the point file changes. Good work

**Review by Mohitkumar33 — APPROVED** [review]
code is clean

**Review by tanishk15sharma — APPROVED** [review]
good practices are followed . you are merge

**Pull request merged**
